### ISSUE TITLE
Ethernet port is used for Extron Out over CatX DTP or HDBaseT.

### ISSUE THREAD

**Issue by EventReplay** [bitfocus/companion-module-extron-in1604#2]
@JeffreyDavidsz 
I'm pretty sure that the IN1604 will not work! The Ethernet port is used for Extron Out over CatX DTP or HDBaseT NOT Networking.

IN1606/08 should work fine with this module, maybe a name change might be in order.
IN1606/08 Manual:
http://www.extron.com/download/files/userman/68-2290-01_B.pdf

**Comment by JeffreyDavidsz** [comment]
When you use the rs-232 port of this switcher,.it will work. The manual I got was from a 1604

**Comment by EventReplay** [comment]
@JeffreyDavidsz 
I didn't think I could do that without an IP2RS232 box?
IN1604 Manual: (more sis commands than in setup pdf referenced)
https://www.extron.com/download/files/userman/68-2631-01_B.pdf
Thank-you
